import type { Transaction } from '@/models/Transaction';
import { deleteFromDB } from '@/utils/db';
import { addEntity,deleteEntities,fetchStreamedEntities,getEntity,getStoredEntities,updateEntity } from './entityService';
const URL = '/api/transactions';
export const fetchTransactions = (year: number) => fetchStreamedEntities(`${URL}/get-since/${new Date(Date.UTC(year, 0, 1)).toISOString()}`, 'transactions');
export const getStoredTransactions = () => getStoredEntities<Transaction>('transactions');
export const getTransactionById = (id: string) => getEntity<Transaction>('transactions', id);
export const addTransaction = (transaction: Partial<Transaction>) => addEntity(URL, 'transactions', transaction);
export const updateTransaction = (id: string, transaction: Partial<Transaction>) => updateEntity(URL, 'transactions', id, transaction);
export const deleteTransactions = (ids: string[]) => deleteEntities(URL, 'transactions', ids);
export const deleteTransactionsLocally = (ids: string[]) => Promise.all(ids.map(id => deleteFromDB('transactions', id)));
